**NB** : **Pour l'emaciation(wasting)**

# Librairies

### Lecture

In [1]:
import pandas as pd
import numpy as np

### Autres

# Lecture

In [2]:
df = pd.read_parquet('../data/clean/model_wasting.parquet')

print(f"Taille : {df.shape}")

Taille : (4864, 15)

In [3]:
df.head()

,age_mois,region,edu_mere,electricite,cuisiniere,toilettes,age_gardien,taille_menage,lavage_mains,telephone,waste,grappe,menage,id_menage,ligne_enfant
0,33,Maritime,Primaire,Réseau,Feu ouvert,Chasse d'eau,37,5,Aucun lieu ou refus,1,0,1,7,1-7,5
1,41,Maritime,Primaire,Réseau,Combustible solide (cuisinière),Latrine améliorée,28,2,Aucun lieu ou refus,1,0,1,15,1-15,2
2,12,Maritime,Aucune,Réseau,Combustible solide (cuisinière),Non améliorée,39,6,Aucun lieu ou refus,1,0,1,18,1-18,6
3,22,Maritime,Aucune,Réseau,Combustible solide (cuisinière),Non améliorée,26,4,Aucun lieu ou refus,1,0,2,1,2-1,4
4,3,Maritime,Secondaire ou plus,Réseau,Combustible solide (cuisinière),Latrine améliorée,31,2,Ustensile mobile,1,0,2,2,2-2,2

# Separation features / label

In [10]:
df.columns

Index(['age_mois', 'region', 'edu_mere', 'electricite', 'cuisiniere',
       'toilettes', 'age_gardien', 'taille_menage', 'lavage_mains',
       'telephone', 'waste', 'grappe', 'menage', 'id_menage', 'ligne_enfant'],
      dtype='object')

In [4]:
NON_ENTREES = ["grappe", "menage", "id_menage", "ligne_enfant", 'waste']

In [5]:
X = df.drop(columns=NON_ENTREES)
y = df['waste']

In [6]:
print(f"\nVérification : {X.columns.tolist()}")

Vérification : ['age_mois', 'region', 'edu_mere', 'electricite', 'cuisiniere', 'toilettes', 'age_gardien', 'taille_menage', 'lavage_mains', 'telephone']

In [7]:
y.unique()

array([0, 1], dtype=int8)

In [9]:
X.head()

,age_mois,region,edu_mere,electricite,cuisiniere,toilettes,age_gardien,taille_menage,lavage_mains,telephone
0,33,Maritime,Primaire,Réseau,Feu ouvert,Chasse d'eau,37,5,Aucun lieu ou refus,1
1,41,Maritime,Primaire,Réseau,Combustible solide (cuisinière),Latrine améliorée,28,2,Aucun lieu ou refus,1
2,12,Maritime,Aucune,Réseau,Combustible solide (cuisinière),Non améliorée,39,6,Aucun lieu ou refus,1
3,22,Maritime,Aucune,Réseau,Combustible solide (cuisinière),Non améliorée,26,4,Aucun lieu ou refus,1
4,3,Maritime,Secondaire ou plus,Réseau,Combustible solide (cuisinière),Latrine améliorée,31,2,Ustensile mobile,1